### ISSUE TITLE
 `require_relative': cannot load such file

### ISSUE THREAD

**Issue by Moriort** [jaynetics/delete_recursively#1]
Hi, i have obtain the next error after install delete_recursively

```
C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/delete_recursively-1.0.0/lib/delete_recursively.rb:7:in `require_relative': cannot load such file -- C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/delete_recursively-1.0.0/lib/delete_recursively/version (LoadError)
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/delete_recursively-1.0.0/lib/delete_recursively.rb:7:in `<module:DeleteRecursively>'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/delete_recursively-1.0.0/lib/delete_recursively.rb:6:in `<top (required)>'
        from C:/Bitnami/rubystack-2.3.4-0/test-app/config/application.rb:5:in `require'
        from C:/Bitnami/rubystack-2.3.4-0/test-app/config/application.rb:5:in `<top (required)>'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `require'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/Bitnami/rubystack-2.3.4-0/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
What happened?

**Comment by jaynetics** [comment]
Thanks for reporting this, @Moriort !

Please try v1.0.1 of this gem, where this should be fixed.
